version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flaskapp:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPWD: mypassword
      DATABASE: employee_db
    depends_on:
      - mysql

volumes:
  mysql_data:
