apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init_db.sql: |
    CREATE DATABASE IF NOT EXISTS employees;
    USE employees;
    CREATE TABLE IF NOT EXISTS employees (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL,
      role VARCHAR(50) NOT NULL
    );
