name: Capstone Project CI/CD Pipeline
on: [pull_request, push]
jobs:
    build-push-deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to ACR
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_REPO }}
            username: github-token
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Build and push Docker image
          run: |
            docker build -t ${{ secrets.ACR_REPO }}/flaskapp:v${{ github.run_number }} .
            docker tag ${{ secrets.ACR_REPO }}/flaskapp:v${{ github.run_number }} ${{ secrets.ACR_REPO }}/flaskapp:latest
            docker push ${{ secrets.ACR_REPO }}/flaskapp:v${{ github.run_number }}
            docker push ${{ secrets.ACR_REPO }}/flaskapp:latest

        - name: Trivy Container Scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: ${{ secrets.ACR_REPO }}/flaskapp:v${{ github.run_number }}
            format: 'table'
            exit-code: '1'
            vuln-type: "os,library"
            severity: 'CRITICAL,HIGH'
            ignore-unfixed: true

        - name: Update Kubernetes manifests
          run: |
            sed -i 's|image: myreg61712.azurecr.io/flaskapp:latest|image: '${{ secrets.ACR_REPO }}/flaskapp:v${{ github.run_number }}'|g' kubernetes/flaskapp.yaml

        - name: Login to Azure using OIDC
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            

        - name: Get AKS credentials
          uses: azure/aks-set-context@v2
          with:
            resource-group: Training-RG
            cluster-name: akscluster

        - name: Deploy to AKS
          run: |
            kubectl apply -f kubernetes/